name: Android Instrumented Tests (Espresso)

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"
  # Allow manual runs from the Actions tab
  workflow_dispatch:

# Avoid overlapping runs when a prior job is still executing
concurrency:
  group: espresso-instrumented-main
  cancel-in-progress: true

jobs:
  connected-tests:
    # Ensure this only runs for main when scheduled; allow manual runs always
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: true
      ADB_INSTALL_TIMEOUT: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run instrumented tests on emulator (mockDebug)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: ./gradlew --no-daemon connectedMockDebugAndroidTest

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-instrumented-test-reports
          path: |
            app/build/reports/androidTests/connected
            app/build/reports/tests

